baseurl: ""
url: "https://eldina07.github.io"

title: A little page about what I do
description: I'm a network developer and I try to share contents about that

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme 

markdown: kramdown
highlighter: rouge
