title: Arnaud ELDIN
email: eldinarnaud@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about network, voip, dev, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: https://eldina07.github.io
twitter_username: eldinarn
github_username:  eldina07

theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

languages: ["en", "fr"]
exclude_from_localizations: ["javascript", "images", "css"]
